services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: niqs_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - niqs_network

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: niqs_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://194.62.54.28:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - niqs_network

  redis:
    image: redis:latest
    container_name: niqs_redis
    ports:
      - "6379:6379"
    networks:
      - niqs_network

  postgres:
    image: postgres:15
    container_name: niqs_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ozer_user
      POSTGRES_PASSWORD: ozer_password
      POSTGRES_DB: ram_metrics_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - niqs_network

  grafana:
    image: grafana/grafana:latest
    container_name: niqs_grafana
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - niqs_network

networks:
  niqs_network:
    driver: bridge

volumes:
  pgdata:
